import React from 'react';
import {
  Home,
  User,
  Settings,
  ShoppingCart,
  CreditCard,
  FileText,
  Calculator,
  Phone,
  Mail,
  Search,
  Plus,
  Minus,
  Check,
  X,
  Edit,
  Trash2,
  Download,
  Upload,
  Share,
  Heart,
  Star,
  MessageCircle,
  Bell,
  Calendar,
  Clock,
  MapPin,
  Camera,
  Image,
  Video,
  Music,
  Play,
  Pause,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  Info,
  AlertTriangle,
  CheckCircle,
  XCircle,
  HelpCircle,
  ExternalLink,
  Copy,
  Save,
  Send,
  Reply,
  Archive,
  Bookmark,
  Filter,
  Grid,
  List,
  Menu,
  MoreHorizontal,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  RefreshCw,
  ZoomIn,
  ZoomOut,
  Folder,
  File,
  Cloud,
  Globe,
  Link,
  Code,
  Package,
  Truck,
  DollarSign,
  TrendingUp,
  TrendingDown,
  BarChart,
  Activity,
  Zap,
  Award,
  Gift,
  Trophy,
  Target,
  Compass,
  Navigation,
  Briefcase,
  Building,
  Store
} from 'lucide-react';

export const AVAILABLE_ICONS = [
  { name: 'Home', label: 'Главная', icon: Home },
  { name: 'User', label: 'Пользователь', icon: User },
  { name: 'Settings', label: 'Настройки', icon: Settings },
  { name: 'ShoppingCart', label: 'Корзина', icon: ShoppingCart },
  { name: 'CreditCard', label: 'Карта', icon: CreditCard },
  { name: 'FileText', label: 'Документ', icon: FileText },
  { name: 'Calculator', label: 'Калькулятор', icon: Calculator },
  { name: 'Phone', label: 'Телефон', icon: Phone },
  { name: 'Mail', label: 'Почта', icon: Mail },
  { name: 'Search', label: 'Поиск', icon: Search },
  { name: 'Plus', label: 'Плюс', icon: Plus },
  { name: 'Minus', label: 'Минус', icon: Minus },
  { name: 'Check', label: 'Галочка', icon: Check },
  { name: 'X', label: 'Крестик', icon: X },
  { name: 'Edit', label: 'Редактировать', icon: Edit },
  { name: 'Trash2', label: 'Удалить', icon: Trash2 },
  { name: 'Download', label: 'Скачать', icon: Download },
  { name: 'Upload', label: 'Загрузить', icon: Upload },
  { name: 'Share', label: 'Поделиться', icon: Share },
  { name: 'Heart', label: 'Сердце', icon: Heart },
  { name: 'Star', label: 'Звезда', icon: Star },
  { name: 'MessageCircle', label: 'Сообщение', icon: MessageCircle },
  { name: 'Bell', label: 'Уведомление', icon: Bell },
  { name: 'Calendar', label: 'Календарь', icon: Calendar },
  { name: 'Clock', label: 'Часы', icon: Clock },
  { name: 'MapPin', label: 'Местоположение', icon: MapPin },
  { name: 'Camera', label: 'Камера', icon: Camera },
  { name: 'Image', label: 'Изображение', icon: Image },
  { name: 'Video', label: 'Видео', icon: Video },
  { name: 'Music', label: 'Музыка', icon: Music },
  { name: 'Play', label: 'Воспроизвести', icon: Play },
  { name: 'Pause', label: 'Пауза', icon: Pause },
  
  { name: 'Lock', label: 'Замок', icon: Lock },
  { name: 'Unlock', label: 'Разблокировать', icon: Unlock },
  { name: 'Eye', label: 'Глаз', icon: Eye },
  { name: 'EyeOff', label: 'Скрыть', icon: EyeOff },
  { name: 'Info', label: 'Информация', icon: Info },
  { name: 'AlertTriangle', label: 'Предупреждение', icon: AlertTriangle },
  { name: 'CheckCircle', label: 'Успех', icon: CheckCircle },
  { name: 'XCircle', label: 'Ошибка', icon: XCircle },
  { name: 'HelpCircle', label: 'Помощь', icon: HelpCircle },
  { name: 'ExternalLink', label: 'Внешняя ссылка', icon: ExternalLink },
  { name: 'Copy', label: 'Копировать', icon: Copy },
  { name: 'Save', label: 'Сохранить', icon: Save },
  { name: 'Send', label: 'Отправить', icon: Send },
  { name: 'Reply', label: 'Ответить', icon: Reply },
  { name: 'Archive', label: 'Архив', icon: Archive },
  { name: 'Bookmark', label: 'Закладка', icon: Bookmark },
  { name: 'Filter', label: 'Фильтр', icon: Filter },
  { name: 'Grid', label: 'Сетка', icon: Grid },
  { name: 'List', label: 'Список', icon: List },
  { name: 'Menu', label: 'Меню', icon: Menu },
  { name: 'MoreHorizontal', label: 'Ещё', icon: MoreHorizontal },
  { name: 'ChevronUp', label: 'Вверх', icon: ChevronUp },
  { name: 'ChevronDown', label: 'Вниз', icon: ChevronDown },
  { name: 'ChevronLeft', label: 'Влево', icon: ChevronLeft },
  { name: 'ChevronRight', label: 'Вправо', icon: ChevronRight },
  { name: 'RefreshCw', label: 'Обновить', icon: RefreshCw },
  { name: 'ZoomIn', label: 'Увеличить', icon: ZoomIn },
  { name: 'ZoomOut', label: 'Уменьшить', icon: ZoomOut },
  { name: 'Folder', label: 'Папка', icon: Folder },
  { name: 'File', label: 'Файл', icon: File },
  { name: 'Cloud', label: 'Облако', icon: Cloud },
  { name: 'Globe', label: 'Глобус', icon: Globe },
  { name: 'Link', label: 'Ссылка', icon: Link },
  { name: 'Code', label: 'Код', icon: Code },
  { name: 'Package', label: 'Пакет', icon: Package },
  { name: 'Truck', label: 'Грузовик', icon: Truck },
  { name: 'DollarSign', label: 'Доллар', icon: DollarSign },
  { name: 'TrendingUp', label: 'Рост', icon: TrendingUp },
  { name: 'TrendingDown', label: 'Падение', icon: TrendingDown },
  { name: 'BarChart', label: 'Диаграмма', icon: BarChart },
  { name: 'Activity', label: 'Активность', icon: Activity },
  { name: 'Zap', label: 'Молния', icon: Zap },
  { name: 'Award', label: 'Награда', icon: Award },
  { name: 'Gift', label: 'Подарок', icon: Gift },
  { name: 'Trophy', label: 'Кубок', icon: Trophy },
  { name: 'Target', label: 'Цель', icon: Target },
  { name: 'Compass', label: 'Компас', icon: Compass },
  { name: 'Navigation', label: 'Навигация', icon: Navigation },
  { name: 'Briefcase', label: 'Портфель', icon: Briefcase },
  { name: 'Building', label: 'Здание', icon: Building },
  { name: 'Store', label: 'Магазин', icon: Store }
];

export const getIconComponent = (iconName: string): React.ComponentType<{ size?: number; className?: string }> => {
  const iconMap: Record<string, React.ComponentType<any>> = {
    Home,
    User,
    Settings,
    ShoppingCart,
    CreditCard,
    FileText,
    Calculator,
    Phone,
    Mail,
    Search,
    Plus,
    Minus,
    Check,
    X,
    Edit,
    Trash2,
    Download,
    Upload,
    Share,
    Heart,
    Star,
    MessageCircle,
    Bell,
    Calendar,
    Clock,
    MapPin,
    Camera,
    Image,
    Video,
    Music,
    Play,
    Pause,
    
    Lock,
    Unlock,
    Eye,
    EyeOff,
    Info,
    AlertTriangle,
    CheckCircle,
    XCircle,
    HelpCircle,
    ExternalLink,
    Copy,
    Save,
    Send,
    Reply,
    Archive,
    Bookmark,
    Filter,
    Grid,
    List,
    Menu,
    MoreHorizontal,
    ChevronUp,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    RefreshCw,
    ZoomIn,
    ZoomOut,
    Folder,
    File,
    Cloud,
    Globe,
    Link,
    Code,
    Package,
    Truck,
    DollarSign,
    TrendingUp,
    TrendingDown,
    BarChart,
    Activity,
    Zap,
    Award,
    Gift,
    Trophy,
    Target,
    Compass,
    Navigation,
    Briefcase,
    Building,
    Store
  };

  return iconMap[iconName] || (() => null);
};