// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqhuwvveovmfyihjnanx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxaHV3dnZlb3ZtZnlpaGpuYW54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwODM4MjUsImV4cCI6MjA2ODY1OTgyNX0.AZ-hINDCe8C6FQ89Sg5uq6SB3DAsmB_jW_wOj467mfY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});