-- Create currencies table
CREATE TABLE public.currencies (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  eur_rub numeric NOT NULL,
  cny_rub numeric NOT NULL,
  usd_rub numeric NOT NULL,
  usd_cny numeric NOT NULL,
  CONSTRAINT currencies_pkey PRIMARY KEY (id)
);

-- Enable RLS
ALTER TABLE public.currencies ENABLE ROW LEVEL SECURITY;

-- RLS Policies
-- Anyone can view currency rates (public information)
CREATE POLICY "Anyone can view currency rates" 
  ON public.currencies 
  FOR SELECT 
  USING (true);

-- Only admins can insert currency rates
CREATE POLICY "Admins can insert currency rates" 
  ON public.currencies 
  FOR INSERT 
  WITH CHECK (get_current_user_type() = ANY (ARRAY['ww_manager'::text, 'ww_developer'::text]));

-- Only admins can update currency rates
CREATE POLICY "Admins can update currency rates" 
  ON public.currencies 
  FOR UPDATE 
  USING (get_current_user_type() = ANY (ARRAY['ww_manager'::text, 'ww_developer'::text]));

-- Only admins can delete currency rates
CREATE POLICY "Admins can delete currency rates" 
  ON public.currencies 
  FOR DELETE 
  USING (get_current_user_type() = ANY (ARRAY['ww_manager'::text, 'ww_developer'::text]));